export const ADD_QUESTION = 'ADD_QUESTION'
export const UPDATE_FORM = 'UPDATE_FORM'
export const SAVE_FORM = 'SAVE_FORM'
export const SHOW_LOADER = 'SHOW_LOADER'
export const SET_FORM_URL = 'SET_FORM_URL'
export const GET_ALL_FORM = 'GET_ALL_FORM'
